### ISSUE TITLE
no-unstable-api-use: allow specifying tags to check

### ISSUE THREAD

**Issue by ajafff** [fimbullinter/wotan#254]
```yaml
rules:
  no-unsable-api-use:
    options:
      tags:
        - deprecated
        - experimental
```

This allows users to only check `@deprecated` and ignore `@experimental`, or add some custom tags to the list.

This is especially useful when working with Angular where large parts of the public API are marked `@experimental`.

/cc @CSchulz

**Comment by CSchulz** [comment]
I think just excluding some tags would be a good start, but in the future it would be nice to be able to whitelist some modules. Sometimes you want only to allow the usage of some experimental features of a specific module and not all.

**Comment by ajafff** [comment]
> whitelist some modules

I guess you mean per tag? That is: allow `@experimental` from `@angular/core`, but still complain about `@deprecated`  APIs from every module.

I think this could be implemented using a glob pattern, so you could also whitelist `@angular/core/**` to match `@angular/core` and `@angular/core/testing`. That would also work with patterns like `@angular/**` which whitelists everything from Angular...

```yaml
rules:
  no-unsable-api-use:
    options:
      tags:
        - deprecated
        - tag: experimental
          whitelist: "@angular/core/**"
```

**Comment by CSchulz** [comment]
Yeah I think this is a good approach, but I am not sure if it is good enough.

In our case we have the `forwardRef` function, which is marked as experimental, but I don't want to allow every experimental feature of the core.

**Comment by ajafff** [comment]
You're right. Here's another try:

```yaml
rules:
  no-unsable-api-use:
    options:
      tags:
        - deprecated
        - experimental
      ignore:
        - "@angular/core": forwardRef # allow 'forwardRef' from '@angular/core'
        - "@my-experiments/**": # allow everything from any package in the '@my-experiments' scope
        - my-module: # allow 'symbolA' and 'symbolB' from 'my-module'
          - symbolA
          - symbolB
```
