### ISSUE TITLE
Wotan lints excluded files.

### ISSUE THREAD

**Issue by gustofbreak** [fimbullinter/wotan#387]
## Meta

wotan 0.12.0
tsc 3.0.1

How did you run wotan? CLI

## Configuration

```yaml
rules:
  await-async-result:
    rule: await-async-result
    severity: error
  await-only-promise:
    rule: await-only-promise
    severity: error
  ban-dom-globals:
    rule: ban-dom-globals
    severity: error
  delete-only-optional-property:
    rule: delete-only-optional-property
    severity: error
  generator-require-yield:
    rule: generator-require-yield
    severity: error
  new-parens:
    rule: new-parens
    severity: error
  no-case-declaration:
    rule: no-case-declaration
    severity: error
  no-debugger:
    rule: no-debugger
    severity: error
  no-duplicate-case:
    rule: no-duplicate-case
    severity: error
  no-duplicate-spread-property:
    rule: no-duplicate-spread-property
    severity: error
  no-fallthrough:
    rule: no-fallthrough
    severity: error
  no-inferred-empty-object:
    rule: no-inferred-empty-object
    severity: error
  no-invalid-assertion:
    rule: no-invalid-assertion
    severity: error
  no-misused-generics:
    rule: no-misused-generics
    severity: error
  no-nan-compare:
    rule: no-nan-compare
    severity: error
  no-octal-escape:
    rule: no-octal-escape
    severity: error
  no-return-await:
    rule: no-return-await
    severity: error
  no-unassigned-variable:
    rule: no-unassigned-variable
    severity: error
  no-unreachable-code:
    rule: no-unreachable-code
    severity: error
  no-unsafe-finally:
    rule: no-unsafe-finally
    severity: error
  no-unstable-api-use:
    rule: no-unstable-api-use
    severity: error
  no-unused-expression:
    rule: no-unused-expression
    severity: error
  no-unused-label:
    rule: no-unused-label
    severity: error
  no-useless-assertion:
    rule: no-useless-assertion
    severity: 'off'
  no-useless-declare:
    rule: no-useless-declare
    severity: error
  no-useless-initializer:
    rule: no-useless-initializer
    severity: error
  no-useless-jump-label:
    rule: no-useless-jump-label
    severity: error
  no-useless-predicate:
    rule: no-useless-predicate
    severity: 'off'
  no-useless-spread:
    rule: no-useless-spread
    severity: error
  prefer-const:
    rule: prefer-const
    severity: error
  prefer-dot-notation:
    rule: prefer-dot-notation
    severity: error
  prefer-for-of:
    rule: prefer-for-of
    severity: error
  prefer-namespace-keyword:
    rule: prefer-namespace-keyword
    severity: error
  prefer-number-methods:
    rule: prefer-number-methods
    severity: error
  prefer-object-spread:
    rule: prefer-object-spread
    severity: error
  return-never-call:
    rule: return-never-call
    severity: error
  syntaxcheck:
    rule: syntaxcheck
    severity: error
  trailing-newline:
    rule: trailing-newline
    severity: error
  try-catch-return-await:
    rule: try-catch-return-await
    severity: error
  tslint/interface-name:
    options: always-prefix
    rule: interface-name
    rulesDirectories:
      -/path/to/project/root
    severity: error
  typecheck:
    rule: typecheck
    severity: error
```

## Code

I have `@types/next` (with a small modification) installed at `<project root>/types/next` and symlink node_modules/@types/next to that path.

Running `wotan` ignores other `node_module`s fine, but it complains regarding `<project root>/types/next`, no matter how I set `exclude` in tsconfig.json.

I tried this code:

```bash
$ wotan -p ./tsconfig.json \
  -m @fimbul/heimdall # for tslint/interface-name
```

tsconfig.json

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "experimentalDecorators": true,
    "jsx": "preserve",
    "lib": [
      "dom",
      "es2015",
      "es2016"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "paths": {
      "~/*": ["*"]
    },
    "preserveConstEnums": true,
    "removeComments": false,
    "skipLibCheck": true,
    "sourceMap": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "target": "esnext"
  },
  "exclude": [
    ".next",
    "node_modules",
    "types/next"
  ]
}
```

I expected to see this happen: Linting succeeds with ./types/next ignored.

Instead, this happened:

```bash
/path/to/project/types/next/index.d.ts:27:15
ERROR 27:15     tslint/interface-name  interface name must start with a capitalized I
ERROR 47:15     tslint/interface-name  interface name must start with a capitalized I
ERROR 54:15     tslint/interface-name  interface name must start with a capitalized I
ERROR 68:15     tslint/interface-name  interface name must start with a capitalized I
ERROR 76:15     tslint/interface-name  interface name must start with a capitalized I

...
```
