### ISSUE TITLE
Fine-grained control which rules are autofixed

### ISSUE THREAD

**Issue by ajafff** [fimbullinter/wotan#419]
Sometimes I find myself in the need to autofix only a subset of the enabled rules, for example when updating the linter configuration of existing projects.
Although Fimbullinter tries to only ship safe fixes in core rules, that's not necessarily the case with 3rd party rules.

One possibility is amending the config for fixing to enable only the desired rules and revert that change afterwards. But as mentioned above, there might be rules with unsafe fixes in your config. So this approach is not a long-term solution.

Instead this could be an additional config option in `.wotanrc.yaml`:

```yaml
rules:
  prefer-const:
    severity: error
    fix: false
  trailing-comma: error # fix defaults to 'true' if not specified
```

Inheritance of that new option works the same as `severity` and `options`. Only the specified options are overridden while all others are inherited by the parent config.

Note that even if `fix: true` is specified for any rule, autofixing will only be done if `--fix` CLI option is enabled (or the `Linter#lintAndFix` API is used).

Related: https://github.com/palantir/tslint/issues/2039
