### ISSUE TITLE
tslint and typecheck implementation for vue file

### ISSUE THREAD

**Issue by rumanbsl** [fimbullinter/wotan#528]
Hello, I am trying to integrate both tslint and typecheck for .vue file. I followed the recipe, but I am doing something wrong.
``` 
//wotanrc.yaml
rules:
  # your other rules go here
  syntaxcheck: error # could also be 'warning'
  typecheck: error # could also be 'warning'
```
```
//.fimbullinter.yaml
config: ./.wotanrc.yaml
valtyr:
  overrides:
    - files: "*.vue"
      processor: "@fimbul/ve"
project: tsconfig.json
exclude:
  - "**/*.d.ts"
  - "surveyEditor"
```

from the cli I am running `wotan -m @fimbul/valtyr --fix`

still no luck. FYI tslint works if i dont reference the `.wotanrc.yaml`, but typecheck is leftout in that situation.
