### ISSUE TITLE
Heimdall config example doesn't work?

### ISSUE THREAD

**Issue by Ovyerus** [fimbullinter/wotan#593]
Trying to use heimdall and wotan for a project, and I'm following what the example says to do for `rulesDirectories`, but it doesn't seem to be working

```yaml
extends: wotan:recommended
module: '@wotan/heimdall'

rulesDirectories:
  tslint: .

rules:
  # rules
```

However when I attempt to then use wotan, the console gets filled with
```
Could not find rule '<tslint rule>' in E:\jetty\frontend.
```
